config/routes.rb
Rails.application.routes.draw do
  
  get '/url/new'
  post '/url/new' => 'url#create'

  get '/url/:id' => 'url#show', as: 'url'

end

app/models/url.rb
class Url < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/url_controller.rb
class UrlController < ApplicationController

  def new
    @urls = Url.all
  end

  def show
    @url = Url.find(params[:id])
    redirect_to "#{@url.user_url}"
  end

  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to url_new_path(id: @url.id) } 
        format.all { render plain: "We only support HTML", status: :not_acceptable }
      else
        format.html { render :new }
      end
    end
  end

  private

  def url_params
    params.require(:url).permit(:user_url, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_helper.rb
module UrlHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shorty</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/url/new.html.erb
<h3><%= url_url(params[:id]) if params[:id] %></h3>
<div class="form">
  <h1>Enter your URL</h1>
  <%= form_for(:url) do |f| %>
    <div class="field">
      <%= f.text_field :user_url %>
    </div>
    <div class="action">
      <%= f.submit "Shorten" %>
    </div>
  <% end %>
</div>

app/views/url/show.html.erb
<h1>Here is your shortened url:</h1>
<%= @url %>
<%= link_to @url.user_url do %>
  <% url_url %>
<% end %>